name: CI

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main]

jobs:
  test-cli:
    name: Test CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint CLI
        run: npm run lint --workspace=packages/cli

      - name: Test CLI
        run: npm run test --workspace=packages/cli

  test-web:
    name: Test Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint Web
        run: npm run lint --workspace=packages/web

      - name: Test Web
        run: npm run test:run --workspace=packages/web

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [test-cli, test-web]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build CLI
        run: npm run build:cli

      - name: Build Web
        run: npm run build:web