name: Deploy Web to GitHub Pages

on:
  push:
    branches: [master, main]
    paths:
      - 'packages/web/**'
      - '.github/workflows/web-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  NODE_VERSION: '22'

jobs:
  build:
    name: Build for Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web application
        run: npm run build:web
        env:
          NODE_ENV: production

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        working-directory: ./packages/web

      - name: Run E2E tests on production build
        run: npm run test:e2e -- --project=chromium
        working-directory: ./packages/web
        env:
          NODE_ENV: production

      - name: Upload E2E test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./packages/web/playwright-report/
          retention-days: 7

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/web/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4