name: Deploy Web to GitHub Pages

on:
  push:
    branches: [master, main]
    paths:
      - 'packages/web/**'
      - '.github/workflows/web-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  NODE_VERSION: '22'

jobs:
  build:
    name: Build for Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download sample database
        run: |
          mkdir -p packages/web/public/data
          curl -L -o packages/web/public/data/sample.db \
            https://github.com/neonwatty/fscrape/releases/download/sample-data-v1/sample.db
          echo "Downloaded sample database ($(du -h packages/web/public/data/sample.db | cut -f1))"

      - name: Build web application
        run: npm run build:web
        env:
          NODE_ENV: production

      - name: Copy SQL.js WASM files
        run: |
          mkdir -p packages/web/out/sql-js
          cp node_modules/sql.js/dist/sql-wasm.wasm packages/web/out/sql-js/
          cp node_modules/sql.js/dist/sql-wasm.js packages/web/out/sql-js/
          echo "Copied SQL.js WASM files"
          echo "WASM file size: $(du -h packages/web/out/sql-js/sql-wasm.wasm | cut -f1)"
          echo "JS file size: $(du -h packages/web/out/sql-js/sql-wasm.js | cut -f1)"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/web/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4